### ISSUE TITLE
Tagging/Versioning

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo-starter#67]
dojo-starter should be versioned & tag to match dojo version

**Comment by notV4l** [comment]
Since dojo-starter is cloned when doing sozo init, it should always match the dojo version used.
Maybe dojo-starter should move into main repo

**Comment by glihm** [comment]
We could imagine:

1. Dojo CI triggering the PR to update the version here.
2. Adding a CI workflow to bump the version + adding the tag automatically to be fetched by sozo.
